# Generated by Django 3.0.5 on 2021-06-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default=None, max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Ayr', 'Ayr'), ('Nottingham', 'Nottingham'), ('Warwick', 'Warwick'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Market Rasen', 'Market Rasen'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Dundalk', 'Dundalk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby')], default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Ayr', 'Ayr'), ('Nottingham', 'Nottingham'), ('Warwick', 'Warwick'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Market Rasen', 'Market Rasen'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Dundalk', 'Dundalk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Ayr', 'Ayr'), ('Nottingham', 'Nottingham'), ('Warwick', 'Warwick'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Market Rasen', 'Market Rasen'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Dundalk', 'Dundalk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Ayr', 'Ayr'), ('Nottingham', 'Nottingham'), ('Warwick', 'Warwick'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Market Rasen', 'Market Rasen'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Dundalk', 'Dundalk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Ayr', 'Ayr'), ('Nottingham', 'Nottingham'), ('Warwick', 'Warwick'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Market Rasen', 'Market Rasen'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Dundalk', 'Dundalk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Ayr', 'Ayr'), ('Nottingham', 'Nottingham'), ('Warwick', 'Warwick'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Market Rasen', 'Market Rasen'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Dundalk', 'Dundalk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Ayr', 'Ayr'), ('Nottingham', 'Nottingham'), ('Warwick', 'Warwick'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Market Rasen', 'Market Rasen'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Dundalk', 'Dundalk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
    ]
