# Generated by Django 3.0.5 on 2021-03-04 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('In Service', 'In Service'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='kauto',
            name='date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AlterField(
            model_name='arkle',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Ayr', 'Ayr'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Beverly', 'Beverly'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('York', 'York'), ('Newbury', 'Newbury'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Cartmel', 'Cartmel'), ('Nottingham', 'Nottingham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Taunton', 'Taunton'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Huntingdon', 'Huntingdon')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Ayr', 'Ayr'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Beverly', 'Beverly'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('York', 'York'), ('Newbury', 'Newbury'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Cartmel', 'Cartmel'), ('Nottingham', 'Nottingham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Taunton', 'Taunton'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Huntingdon', 'Huntingdon')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Ayr', 'Ayr'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Beverly', 'Beverly'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('York', 'York'), ('Newbury', 'Newbury'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Cartmel', 'Cartmel'), ('Nottingham', 'Nottingham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Taunton', 'Taunton'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Huntingdon', 'Huntingdon')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Ayr', 'Ayr'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Beverly', 'Beverly'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('York', 'York'), ('Newbury', 'Newbury'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Cartmel', 'Cartmel'), ('Nottingham', 'Nottingham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Taunton', 'Taunton'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Huntingdon', 'Huntingdon')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Ayr', 'Ayr'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Beverly', 'Beverly'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('York', 'York'), ('Newbury', 'Newbury'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Cartmel', 'Cartmel'), ('Nottingham', 'Nottingham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Taunton', 'Taunton'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Huntingdon', 'Huntingdon')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Ayr', 'Ayr'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Beverly', 'Beverly'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('York', 'York'), ('Newbury', 'Newbury'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Cartmel', 'Cartmel'), ('Nottingham', 'Nottingham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Taunton', 'Taunton'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Huntingdon', 'Huntingdon')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
        migrations.CreateModel(
            name='Other_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41)),
                ('venue', models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Ayr', 'Ayr'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Beverly', 'Beverly'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('York', 'York'), ('Newbury', 'Newbury'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Cartmel', 'Cartmel'), ('Nottingham', 'Nottingham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Taunton', 'Taunton'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Huntingdon', 'Huntingdon')], default='Kempton Park', max_length=18, null=True)),
                ('comments', models.TextField(blank=True)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_logs.Other')),
            ],
            options={
                'verbose_name_plural': 'other entries',
            },
        ),
    ]
