# Generated by Django 3.0.5 on 2021-06-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='failure_codes',
            field=models.CharField(blank=True, choices=[('Lights in Grey State', 'Lights in Grey State'), ('USB Connector Broken', 'USB Connector Broken'), ('Battery Failure', 'Battery Failure'), ('Switch Broken', 'Switch Broken'), ('Clear Water Ingress Damage', 'Clear Water Ingress Damage'), ('Case Damaged', 'Case Damaged'), ('Unknown', 'Unknown'), ('Antenna Broken', 'Antenna Broken')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default=None, max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kempton Park', 'Kempton Park'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Chester', 'Chester'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Dundalk', 'Dundalk'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Market Rasen', 'Market Rasen'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('York', 'York'), ('Kelso', 'Kelso')], default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kempton Park', 'Kempton Park'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Chester', 'Chester'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Dundalk', 'Dundalk'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Market Rasen', 'Market Rasen'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('York', 'York'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kempton Park', 'Kempton Park'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Chester', 'Chester'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Dundalk', 'Dundalk'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Market Rasen', 'Market Rasen'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('York', 'York'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kempton Park', 'Kempton Park'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Chester', 'Chester'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Dundalk', 'Dundalk'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Market Rasen', 'Market Rasen'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('York', 'York'), ('Kelso', 'Kelso')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kempton Park', 'Kempton Park'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Chester', 'Chester'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Dundalk', 'Dundalk'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Market Rasen', 'Market Rasen'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('York', 'York'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kempton Park', 'Kempton Park'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Chester', 'Chester'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Dundalk', 'Dundalk'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Market Rasen', 'Market Rasen'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('York', 'York'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Leicester', 'Leicester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kempton Park', 'Kempton Park'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Chester', 'Chester'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Dundalk', 'Dundalk'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Market Rasen', 'Market Rasen'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('York', 'York'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
    ]
