# Generated by Django 3.0.5 on 2021-03-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Taunton', 'Taunton'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Salisbury', 'Salisbury'), ('Chester', 'Chester'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('York', 'York'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Perth', 'Perth'), ('Kelso', 'Kelso'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Taunton', 'Taunton'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Salisbury', 'Salisbury'), ('Chester', 'Chester'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('York', 'York'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Perth', 'Perth'), ('Kelso', 'Kelso'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Taunton', 'Taunton'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Salisbury', 'Salisbury'), ('Chester', 'Chester'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('York', 'York'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Perth', 'Perth'), ('Kelso', 'Kelso'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Taunton', 'Taunton'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Salisbury', 'Salisbury'), ('Chester', 'Chester'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('York', 'York'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Perth', 'Perth'), ('Kelso', 'Kelso'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Taunton', 'Taunton'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Salisbury', 'Salisbury'), ('Chester', 'Chester'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('York', 'York'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Perth', 'Perth'), ('Kelso', 'Kelso'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Taunton', 'Taunton'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Salisbury', 'Salisbury'), ('Chester', 'Chester'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('York', 'York'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Perth', 'Perth'), ('Kelso', 'Kelso'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Taunton', 'Taunton'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Salisbury', 'Salisbury'), ('Chester', 'Chester'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('York', 'York'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Perth', 'Perth'), ('Kelso', 'Kelso'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
    ]
