# Generated by Django 3.0.5 on 2021-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default=None, max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Redcar', 'Redcar'), ('Wetherby', 'Wetherby'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Newmarket', 'Newmarket'), ('Exeter', 'Exeter'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Market Rasen', 'Market Rasen'), ('Newbury', 'Newbury'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Huntingdon', 'Huntingdon'), ('Thirsk', 'Thirsk'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('York', 'York'), ('Carlisle', 'Carlisle'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park')], default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Redcar', 'Redcar'), ('Wetherby', 'Wetherby'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Newmarket', 'Newmarket'), ('Exeter', 'Exeter'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Market Rasen', 'Market Rasen'), ('Newbury', 'Newbury'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Huntingdon', 'Huntingdon'), ('Thirsk', 'Thirsk'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('York', 'York'), ('Carlisle', 'Carlisle'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Redcar', 'Redcar'), ('Wetherby', 'Wetherby'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Newmarket', 'Newmarket'), ('Exeter', 'Exeter'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Market Rasen', 'Market Rasen'), ('Newbury', 'Newbury'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Huntingdon', 'Huntingdon'), ('Thirsk', 'Thirsk'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('York', 'York'), ('Carlisle', 'Carlisle'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Redcar', 'Redcar'), ('Wetherby', 'Wetherby'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Newmarket', 'Newmarket'), ('Exeter', 'Exeter'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Market Rasen', 'Market Rasen'), ('Newbury', 'Newbury'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Huntingdon', 'Huntingdon'), ('Thirsk', 'Thirsk'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('York', 'York'), ('Carlisle', 'Carlisle'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='failures',
            name='code',
            field=models.CharField(blank=True, choices=[('USB Connector Broken', 'USB Connector Broken'), ('Clear Water Ingress Damage', 'Clear Water Ingress Damage'), ('Antenna Broken', 'Antenna Broken'), ('Switch Broken', 'Switch Broken'), ('Case Damaged', 'Case Damaged'), ('Lights in Grey State', 'Lights in Grey State'), ('Battery Failure', 'Battery Failure'), ('Unknown', 'Unknown')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Redcar', 'Redcar'), ('Wetherby', 'Wetherby'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Newmarket', 'Newmarket'), ('Exeter', 'Exeter'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Market Rasen', 'Market Rasen'), ('Newbury', 'Newbury'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Huntingdon', 'Huntingdon'), ('Thirsk', 'Thirsk'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('York', 'York'), ('Carlisle', 'Carlisle'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Redcar', 'Redcar'), ('Wetherby', 'Wetherby'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Newmarket', 'Newmarket'), ('Exeter', 'Exeter'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Market Rasen', 'Market Rasen'), ('Newbury', 'Newbury'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Huntingdon', 'Huntingdon'), ('Thirsk', 'Thirsk'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('York', 'York'), ('Carlisle', 'Carlisle'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Catterick Bridge', 'Catterick Bridge'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Redcar', 'Redcar'), ('Wetherby', 'Wetherby'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Newmarket', 'Newmarket'), ('Exeter', 'Exeter'), ('Leicester', 'Leicester'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Market Rasen', 'Market Rasen'), ('Newbury', 'Newbury'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Huntingdon', 'Huntingdon'), ('Thirsk', 'Thirsk'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('York', 'York'), ('Carlisle', 'Carlisle'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
    ]
