# Generated by Django 3.0.5 on 2020-12-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Refurb', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(choices=[('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('York', 'York'), ('Newbury', 'Newbury'), ('Huntingdon', 'Huntingdon'), ('Perth', 'Perth'), ('Thirsk', 'Thirsk'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Epsom Downs', 'Epsom Downs'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Goodwood', 'Goodwood')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Refurb', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(choices=[('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('York', 'York'), ('Newbury', 'Newbury'), ('Huntingdon', 'Huntingdon'), ('Perth', 'Perth'), ('Thirsk', 'Thirsk'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Epsom Downs', 'Epsom Downs'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Goodwood', 'Goodwood')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Refurb', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(choices=[('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('York', 'York'), ('Newbury', 'Newbury'), ('Huntingdon', 'Huntingdon'), ('Perth', 'Perth'), ('Thirsk', 'Thirsk'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Epsom Downs', 'Epsom Downs'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Goodwood', 'Goodwood')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Refurb', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('York', 'York'), ('Newbury', 'Newbury'), ('Huntingdon', 'Huntingdon'), ('Perth', 'Perth'), ('Thirsk', 'Thirsk'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Epsom Downs', 'Epsom Downs'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Goodwood', 'Goodwood')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Refurb', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(choices=[('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('York', 'York'), ('Newbury', 'Newbury'), ('Huntingdon', 'Huntingdon'), ('Perth', 'Perth'), ('Thirsk', 'Thirsk'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Epsom Downs', 'Epsom Downs'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Goodwood', 'Goodwood')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Refurb', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(choices=[('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Hamilton', 'Hamilton Park'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Haydock', 'Haydock Park'), ('York', 'York'), ('Newbury', 'Newbury'), ('Huntingdon', 'Huntingdon'), ('Perth', 'Perth'), ('Thirsk', 'Thirsk'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Epsom Downs', 'Epsom Downs'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Goodwood', 'Goodwood')], default='Kempton Park', max_length=18),
        ),
    ]
