# Generated by Django 3.0.5 on 2021-06-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default=None, max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('York', 'York'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Redcar', 'Redcar'), ('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Huntingdon', 'Huntingdon'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester')], default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('York', 'York'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Redcar', 'Redcar'), ('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Huntingdon', 'Huntingdon'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('York', 'York'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Redcar', 'Redcar'), ('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Huntingdon', 'Huntingdon'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('York', 'York'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Redcar', 'Redcar'), ('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Huntingdon', 'Huntingdon'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='failures',
            name='code',
            field=models.CharField(blank=True, choices=[('Antenna Broken', 'Antenna Broken'), ('Battery Failure', 'Battery Failure'), ('Lights in Grey State', 'Lights in Grey State'), ('USB Connector Broken', 'USB Connector Broken'), ('Switch Broken', 'Switch Broken'), ('Case Damaged', 'Case Damaged'), ('Clear Water Ingress Damage', 'Clear Water Ingress Damage'), ('Unknown', 'Unknown')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('York', 'York'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Redcar', 'Redcar'), ('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Huntingdon', 'Huntingdon'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('York', 'York'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Redcar', 'Redcar'), ('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Huntingdon', 'Huntingdon'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('York', 'York'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Redcar', 'Redcar'), ('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham'), ('Kempton Park', 'Kempton Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Huntingdon', 'Huntingdon'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester')], default='Kempton Park', max_length=18, null=True),
        ),
    ]
