# Generated by Django 3.0.5 on 2021-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            field=models.CharField(blank=True, choices=[('Case Damaged', 'Case Damaged'), ('USB Connector Broken', 'USB Connector Broken'), ('Clear Water Ingress Damage', 'Clear Water Ingress Damage'), ('Antenna Broken', 'Antenna Broken'), ('Lights in Grey State', 'Lights in Grey State'), ('Switch Broken', 'Switch Broken'), ('Unknown', 'Unknown'), ('Battery Failure', 'Battery Failure')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb')], default=None, max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Hamilton', 'Hamilton Park'), ('Thirsk', 'Thirsk'), ('Market Rasen', 'Market Rasen'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Wincanton', 'Wincanton')], default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Hamilton', 'Hamilton Park'), ('Thirsk', 'Thirsk'), ('Market Rasen', 'Market Rasen'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Wincanton', 'Wincanton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Hamilton', 'Hamilton Park'), ('Thirsk', 'Thirsk'), ('Market Rasen', 'Market Rasen'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Wincanton', 'Wincanton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Hamilton', 'Hamilton Park'), ('Thirsk', 'Thirsk'), ('Market Rasen', 'Market Rasen'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Wincanton', 'Wincanton')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Hamilton', 'Hamilton Park'), ('Thirsk', 'Thirsk'), ('Market Rasen', 'Market Rasen'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Wincanton', 'Wincanton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Hamilton', 'Hamilton Park'), ('Thirsk', 'Thirsk'), ('Market Rasen', 'Market Rasen'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Wincanton', 'Wincanton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Hamilton', 'Hamilton Park'), ('Thirsk', 'Thirsk'), ('Market Rasen', 'Market Rasen'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Wincanton', 'Wincanton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
    ]
