# Generated by Django 3.0.5 on 2021-06-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0002_auto_20210629_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default=None, max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Wincanton', 'Wincanton'), ('Market Rasen', 'Market Rasen'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Carlisle', 'Carlisle'), ('Cheltenham', 'Cheltenham'), ('Epsom Downs', 'Epsom Downs'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Catterick Bridge', 'Catterick Bridge')], default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Wincanton', 'Wincanton'), ('Market Rasen', 'Market Rasen'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Carlisle', 'Carlisle'), ('Cheltenham', 'Cheltenham'), ('Epsom Downs', 'Epsom Downs'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Wincanton', 'Wincanton'), ('Market Rasen', 'Market Rasen'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Carlisle', 'Carlisle'), ('Cheltenham', 'Cheltenham'), ('Epsom Downs', 'Epsom Downs'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Wincanton', 'Wincanton'), ('Market Rasen', 'Market Rasen'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Carlisle', 'Carlisle'), ('Cheltenham', 'Cheltenham'), ('Epsom Downs', 'Epsom Downs'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Catterick Bridge', 'Catterick Bridge')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='failures',
            name='code',
            field=models.CharField(blank=True, choices=[('Clear Water Ingress Damage', 'Clear Water Ingress Damage'), ('Unknown', 'Unknown'), ('Battery Failure', 'Battery Failure'), ('Antenna Broken', 'Antenna Broken'), ('Case Damaged', 'Case Damaged'), ('USB Connector Broken', 'USB Connector Broken'), ('Switch Broken', 'Switch Broken'), ('Lights in Grey State', 'Lights in Grey State')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Wincanton', 'Wincanton'), ('Market Rasen', 'Market Rasen'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Carlisle', 'Carlisle'), ('Cheltenham', 'Cheltenham'), ('Epsom Downs', 'Epsom Downs'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Wincanton', 'Wincanton'), ('Market Rasen', 'Market Rasen'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Carlisle', 'Carlisle'), ('Cheltenham', 'Cheltenham'), ('Epsom Downs', 'Epsom Downs'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Dundalk', 'Dundalk'), ('Wincanton', 'Wincanton'), ('Market Rasen', 'Market Rasen'), ('Thirsk', 'Thirsk'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Sandown Park', 'Sandown Park'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Carlisle', 'Carlisle'), ('Cheltenham', 'Cheltenham'), ('Epsom Downs', 'Epsom Downs'), ('Aintree', 'Aintree'), ('Beverly', 'Beverly'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('Not In Service', 'Not In Service'), ('In Repair', 'In Repair')], default='In Service', max_length=15),
        ),
    ]
