# Generated by Django 3.0.5 on 2021-03-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0002_auto_20210304_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Market Rasen', 'Market Rasen'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Warwick', 'Warwick'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Kempton Park', 'Kempton Park'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Market Rasen', 'Market Rasen'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Warwick', 'Warwick'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Kempton Park', 'Kempton Park'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Market Rasen', 'Market Rasen'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Warwick', 'Warwick'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Kempton Park', 'Kempton Park'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Market Rasen', 'Market Rasen'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Warwick', 'Warwick'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Kempton Park', 'Kempton Park'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Market Rasen', 'Market Rasen'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Warwick', 'Warwick'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Kempton Park', 'Kempton Park'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Market Rasen', 'Market Rasen'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Warwick', 'Warwick'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Kempton Park', 'Kempton Park'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Market Rasen', 'Market Rasen'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Warwick', 'Warwick'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Kempton Park', 'Kempton Park'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
    ]
