# Generated by Django 3.0.5 on 2020-12-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0002_auto_20201231_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Missing', 'Missing'), ('Failed', 'Failed'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('Stick', 'Stick')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(choices=[('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Exeter', 'Exeter'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Epsom Downs', 'Epsom Downs'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Perth', 'Perth'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Wetherby', 'Wetherby'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Missing', 'Missing'), ('Failed', 'Failed'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('Stick', 'Stick')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(choices=[('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Exeter', 'Exeter'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Epsom Downs', 'Epsom Downs'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Perth', 'Perth'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Wetherby', 'Wetherby'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Missing', 'Missing'), ('Failed', 'Failed'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('Stick', 'Stick')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(choices=[('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Exeter', 'Exeter'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Epsom Downs', 'Epsom Downs'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Perth', 'Perth'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Wetherby', 'Wetherby'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Missing', 'Missing'), ('Failed', 'Failed'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('Stick', 'Stick')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Exeter', 'Exeter'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Epsom Downs', 'Epsom Downs'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Perth', 'Perth'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Wetherby', 'Wetherby'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Missing', 'Missing'), ('Failed', 'Failed'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('Stick', 'Stick')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(choices=[('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Exeter', 'Exeter'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Epsom Downs', 'Epsom Downs'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Perth', 'Perth'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Wetherby', 'Wetherby'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Missing', 'Missing'), ('Failed', 'Failed'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('Stick', 'Stick')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(choices=[('Sandown Park', 'Sandown Park'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Exeter', 'Exeter'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Wincanton', 'Wincanton'), ('Epsom Downs', 'Epsom Downs'), ('Newbury', 'Newbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Perth', 'Perth'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Wetherby', 'Wetherby'), ('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Beverly', 'Beverly'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
    ]
