# Generated by Django 3.0.5 on 2021-07-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0002_auto_20210701_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Working', 'Working'), ('Warning', 'Warning'), ('Failure', 'Failure'), ('Repair', 'Repair'), ('OOA', 'Out of Action')], max_length=15)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tracker',
            name='group',
            field=models.CharField(choices=[('Arkle', 'Arkle'), ('Enable', 'Enable'), ('Denman', 'Denman'), ('Frankel', 'Frankel'), ('Kauto', 'Kauto'), ('Winx', 'Winx'), ('Other', 'Other')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Failure',
        ),
        migrations.AddField(
            model_name='entry',
            name='status_tmp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unit_logs.Status'),
        ),
    ]
