# Generated by Django 3.0.5 on 2021-07-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0003_auto_20210705_1725'),
    ]

    def insertStatuses(apps, schema_editor):
      Status = apps.get_model('unit_logs', 'Status')
      Tracker = apps.get_model('unit_logs', 'Tracker')


      Status(category='Working', description='born').save()
      # Now all tracker start_date need to be moved to above category, then tracker_start_date deleted

      Status(category='Working', description='good performance').save()

      Status(category='Warning', description='not to course (gps link failed)').save()
      Status(category='Warning', description='stuck on track').save()

      Status(category='Failure', description='broken power switch').save()
      Status(category='Failure', description='broken connector').save()
      Status(category='Failure', description='no network acquire (no flashing white light)').save()
      Status(category='Failure', description='no network fix (no solid white light)').save()
      Status(category='Failure', description='no charging (no solid red light)').save()
      Status(category='Failure', description='no gps acquire (no flashing orange light)').save()
      Status(category='Failure', description='no gps fix (no solid orange light)').save()
      Status(category='Failure', description='corrupt microprocessor (grey lights)').save()
      Status(category='Failure', description='unknown').save()


      Status(category='Repair', description='in repair').save()
      Status(category='Repair', description='returning to course').save()
      Status(category='Repair', description='broken beyond repair').save()


      Status(category='OOA', description='destroyed').save()
      Status(category='OOA', description='lost').save()

      Status(category='Failure', description='broken battery').save()
      Status(category='OOS', description='temporarily out of service').save()

    operations = [
      migrations.RunPython(insertStatuses)
    ]
