# Generated by Django 3.0.5 on 2020-12-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0003_auto_20201231_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Failed Battery', 'Failed Battery'), ('Refurb', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair'), ('No Solid White', 'No Solid White'), ('Failed', 'Failed'), ('In Service', 'In Service'), ('Connector Broken', 'Connector Broken'), ('Stick', 'Stick'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(choices=[('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Perth', 'Perth'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Leicester', 'Leicester'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Hamilton', 'Hamilton Park')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Failed Battery', 'Failed Battery'), ('Refurb', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair'), ('No Solid White', 'No Solid White'), ('Failed', 'Failed'), ('In Service', 'In Service'), ('Connector Broken', 'Connector Broken'), ('Stick', 'Stick'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(choices=[('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Perth', 'Perth'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Leicester', 'Leicester'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Hamilton', 'Hamilton Park')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Failed Battery', 'Failed Battery'), ('Refurb', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair'), ('No Solid White', 'No Solid White'), ('Failed', 'Failed'), ('In Service', 'In Service'), ('Connector Broken', 'Connector Broken'), ('Stick', 'Stick'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(choices=[('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Perth', 'Perth'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Leicester', 'Leicester'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Hamilton', 'Hamilton Park')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Failed Battery', 'Failed Battery'), ('Refurb', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair'), ('No Solid White', 'No Solid White'), ('Failed', 'Failed'), ('In Service', 'In Service'), ('Connector Broken', 'Connector Broken'), ('Stick', 'Stick'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Perth', 'Perth'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Leicester', 'Leicester'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Hamilton', 'Hamilton Park')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Failed Battery', 'Failed Battery'), ('Refurb', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair'), ('No Solid White', 'No Solid White'), ('Failed', 'Failed'), ('In Service', 'In Service'), ('Connector Broken', 'Connector Broken'), ('Stick', 'Stick'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(choices=[('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Perth', 'Perth'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Leicester', 'Leicester'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Hamilton', 'Hamilton Park')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Failed Battery', 'Failed Battery'), ('Refurb', 'Refurb'), ('No Solid Orange', 'No Solid Orange'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair'), ('No Solid White', 'No Solid White'), ('Failed', 'Failed'), ('In Service', 'In Service'), ('Connector Broken', 'Connector Broken'), ('Stick', 'Stick'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(choices=[('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Perth', 'Perth'), ('Exeter', 'Exeter'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Leicester', 'Leicester'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Hamilton', 'Hamilton Park')], default='Kempton Park', max_length=18),
        ),
    ]
