# Generated by Django 3.0.5 on 2021-03-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0003_auto_20210304_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kauto',
            name='date',
        ),
        migrations.AddField(
            model_name='arkle',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denman',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enable',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frankel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winx',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Redcar', 'Redcar'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Ayr', 'Ayr'), ('Catterick Bridge', 'Catterick Bridge'), ('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('York', 'York'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Thirsk', 'Thirsk'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Redcar', 'Redcar'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Ayr', 'Ayr'), ('Catterick Bridge', 'Catterick Bridge'), ('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('York', 'York'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Thirsk', 'Thirsk'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Redcar', 'Redcar'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Ayr', 'Ayr'), ('Catterick Bridge', 'Catterick Bridge'), ('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('York', 'York'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Thirsk', 'Thirsk'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Redcar', 'Redcar'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Ayr', 'Ayr'), ('Catterick Bridge', 'Catterick Bridge'), ('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('York', 'York'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Thirsk', 'Thirsk'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Redcar', 'Redcar'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Ayr', 'Ayr'), ('Catterick Bridge', 'Catterick Bridge'), ('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('York', 'York'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Thirsk', 'Thirsk'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Redcar', 'Redcar'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Ayr', 'Ayr'), ('Catterick Bridge', 'Catterick Bridge'), ('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('York', 'York'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Thirsk', 'Thirsk'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Redcar', 'Redcar'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Carlisle', 'Carlisle'), ('Ayr', 'Ayr'), ('Catterick Bridge', 'Catterick Bridge'), ('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('York', 'York'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Thirsk', 'Thirsk'), ('Dundalk', 'Dundalk'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
    ]
