# Generated by Django 3.0.5 on 2020-12-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0004_auto_20201231_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('No Solid Orange', 'No Solid Orange'), ('Failed', 'Failed'), ('Failed Battery', 'Failed Battery'), ('No Solid White', 'No Solid White'), ('In Service', 'In Service'), ('Refurb', 'Refurb'), ('Missing', 'Missing'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('Stick', 'Stick'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(choices=[('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Pontefract', 'Pontefract'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('No Solid Orange', 'No Solid Orange'), ('Failed', 'Failed'), ('Failed Battery', 'Failed Battery'), ('No Solid White', 'No Solid White'), ('In Service', 'In Service'), ('Refurb', 'Refurb'), ('Missing', 'Missing'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('Stick', 'Stick'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(choices=[('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Pontefract', 'Pontefract'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('No Solid Orange', 'No Solid Orange'), ('Failed', 'Failed'), ('Failed Battery', 'Failed Battery'), ('No Solid White', 'No Solid White'), ('In Service', 'In Service'), ('Refurb', 'Refurb'), ('Missing', 'Missing'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('Stick', 'Stick'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(choices=[('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Pontefract', 'Pontefract'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('No Solid Orange', 'No Solid Orange'), ('Failed', 'Failed'), ('Failed Battery', 'Failed Battery'), ('No Solid White', 'No Solid White'), ('In Service', 'In Service'), ('Refurb', 'Refurb'), ('Missing', 'Missing'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('Stick', 'Stick'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Pontefract', 'Pontefract'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('No Solid Orange', 'No Solid Orange'), ('Failed', 'Failed'), ('Failed Battery', 'Failed Battery'), ('No Solid White', 'No Solid White'), ('In Service', 'In Service'), ('Refurb', 'Refurb'), ('Missing', 'Missing'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('Stick', 'Stick'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(choices=[('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Pontefract', 'Pontefract'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('No Solid Orange', 'No Solid Orange'), ('Failed', 'Failed'), ('Failed Battery', 'Failed Battery'), ('No Solid White', 'No Solid White'), ('In Service', 'In Service'), ('Refurb', 'Refurb'), ('Missing', 'Missing'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Damaged Case', 'Damaged Case'), ('Never Worked', 'Refurb'), ('Stick', 'Stick'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(choices=[('Cartmel', 'Cartmel'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Pontefract', 'Pontefract'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Wincanton', 'Wincanton'), ('Kelso', 'Kelso'), ('Haydock', 'Haydock Park'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('Goodwood', 'Goodwood'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
    ]
