# Generated by Django 3.0.5 on 2021-07-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0004_auto_20210705_1825'),
    ]

    operations = [
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 6 where status='Connector Broken'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 19 where status='Failed Battery'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 16 where status='In Refurb - Broken beyond repair'" ,),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 14 where status='In Refurb - Send for mechanical repair'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 14 where status='In Repair'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 18 where status='Missing'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 8 where status='No Solid White'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 3 where status='On Course - Racing: Not to course'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 4 where status='On Course - Racing: Stuck on track'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 6 where status='On Course - Test: Broken Connector'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 5 where status='On Course - Test: Broken Switch'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 11 where status='On Course - Test: No Orange'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 9 where status='On Course - Test: No Red'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 8 where status='On Course - Test: No Solid White'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 14 where status='Out of Service and Returned for Refurb'"),
      migrations.RunSQL("update unit_logs_entry set status_tmp_id = 4 where status='Stick'"),
    ]
