# Generated by Django 3.0.5 on 2021-06-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0004_auto_20210304_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kauto',
            name='date',
        ),
        migrations.AddField(
            model_name='arkle_entry',
            name='failure_codes',
            field=models.CharField(blank=True, choices=[('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Aintree', 'Aintree'), ('Wincanton', 'Wincanton'), ('Sandown Park', 'Sandown Park'), ('Ludlow', 'Ludlow'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Pontefract', 'Pontefract')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Aintree', 'Aintree'), ('Wincanton', 'Wincanton'), ('Sandown Park', 'Sandown Park'), ('Ludlow', 'Ludlow'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Pontefract', 'Pontefract')], default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Aintree', 'Aintree'), ('Wincanton', 'Wincanton'), ('Sandown Park', 'Sandown Park'), ('Ludlow', 'Ludlow'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Pontefract', 'Pontefract')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Aintree', 'Aintree'), ('Wincanton', 'Wincanton'), ('Sandown Park', 'Sandown Park'), ('Ludlow', 'Ludlow'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Pontefract', 'Pontefract')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Aintree', 'Aintree'), ('Wincanton', 'Wincanton'), ('Sandown Park', 'Sandown Park'), ('Ludlow', 'Ludlow'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Pontefract', 'Pontefract')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Aintree', 'Aintree'), ('Wincanton', 'Wincanton'), ('Sandown Park', 'Sandown Park'), ('Ludlow', 'Ludlow'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Pontefract', 'Pontefract')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Aintree', 'Aintree'), ('Wincanton', 'Wincanton'), ('Sandown Park', 'Sandown Park'), ('Ludlow', 'Ludlow'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Pontefract', 'Pontefract')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Musselburgh', 'Musselburgh'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Aintree', 'Aintree'), ('Wincanton', 'Wincanton'), ('Sandown Park', 'Sandown Park'), ('Ludlow', 'Ludlow'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Newmarket', 'Newmarket'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Pontefract', 'Pontefract')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
    ]
