# Generated by Django 3.0.5 on 2021-07-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0005_auto_20210705_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
    ]
