# Generated by Django 3.0.5 on 2021-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0005_auto_20210616_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='arkle_entry',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='failure_codes',
            field=models.CharField(blank=True, choices=[('USB Connector Broken', 'USB Connector Broken'), ('Lights in Grey State', 'Lights in Grey State'), ('Unknown', 'Unknown'), ('Switch Broken', 'Switch Broken'), ('Clear Water Ingress Damage', 'Clear Water Ingress Damage'), ('Battery Failure', 'Battery Failure'), ('Antenna Broken', 'Antenna Broken'), ('Case Damaged', 'Case Damaged')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Wetherby', 'Wetherby'), ('Chester', 'Chester'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Thirsk', 'Thirsk'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester'), ('Nottingham', 'Nottingham')], default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Wetherby', 'Wetherby'), ('Chester', 'Chester'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Thirsk', 'Thirsk'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Wetherby', 'Wetherby'), ('Chester', 'Chester'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Thirsk', 'Thirsk'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Wetherby', 'Wetherby'), ('Chester', 'Chester'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Thirsk', 'Thirsk'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester'), ('Nottingham', 'Nottingham')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Wetherby', 'Wetherby'), ('Chester', 'Chester'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Thirsk', 'Thirsk'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Wetherby', 'Wetherby'), ('Chester', 'Chester'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Thirsk', 'Thirsk'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Warwick', 'Warwick'), ('Taunton', 'Taunton'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('York', 'York'), ('Wetherby', 'Wetherby'), ('Chester', 'Chester'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Goodwood', 'Goodwood'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Beverly', 'Beverly'), ('Dundalk', 'Dundalk'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Salisbury', 'Salisbury'), ('Thirsk', 'Thirsk'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester'), ('Nottingham', 'Nottingham')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
    ]
