# Generated by Django 3.0.5 on 2020-12-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0005_auto_20201231_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Connector Broken', 'Connector Broken'), ('No Solid Orange', 'No Solid Orange'), ('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Failed', 'Failed'), ('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(choices=[('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Warwick', 'Warwick'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Connector Broken', 'Connector Broken'), ('No Solid Orange', 'No Solid Orange'), ('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Failed', 'Failed'), ('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(choices=[('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Warwick', 'Warwick'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Connector Broken', 'Connector Broken'), ('No Solid Orange', 'No Solid Orange'), ('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Failed', 'Failed'), ('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(choices=[('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Warwick', 'Warwick'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Connector Broken', 'Connector Broken'), ('No Solid Orange', 'No Solid Orange'), ('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Failed', 'Failed'), ('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Warwick', 'Warwick'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Connector Broken', 'Connector Broken'), ('No Solid Orange', 'No Solid Orange'), ('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Failed', 'Failed'), ('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(choices=[('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Warwick', 'Warwick'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Connector Broken', 'Connector Broken'), ('No Solid Orange', 'No Solid Orange'), ('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Failed', 'Failed'), ('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Never Worked', 'Refurb'), ('In Repair', 'In Repair')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(choices=[('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Nottingham', 'Nottingham'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Huntingdon', 'Huntingdon'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Warwick', 'Warwick'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter'), ('Cheltenham', 'Cheltenham'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Wincanton', 'Wincanton'), ('Perth', 'Perth'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Leicester', 'Leicester'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18),
        ),
    ]
