# Generated by Django 3.0.5 on 2021-06-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0005_auto_20210616_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='arkle_entry',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='failure_codes',
            field=models.CharField(blank=True, choices=[('Antenna Broken', 'Antenna Broken'), ('Case Damaged', 'Case Damaged'), ('USB Connector Broken', 'USB Connector Broken'), ('Switch Broken', 'Switch Broken'), ('Unknown', 'Unknown'), ('Battery Failure', 'Battery Failure'), ('Clear Water Ingress Damage', 'Clear Water Ingress Damage'), ('Lights in Grey State', 'Lights in Grey State')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default=None, max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Thirsk', 'Thirsk'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Aintree', 'Aintree'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Kelso', 'Kelso'), ('Wetherby', 'Wetherby'), ('Catterick Bridge', 'Catterick Bridge'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter')], default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Thirsk', 'Thirsk'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Aintree', 'Aintree'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Kelso', 'Kelso'), ('Wetherby', 'Wetherby'), ('Catterick Bridge', 'Catterick Bridge'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Thirsk', 'Thirsk'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Aintree', 'Aintree'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Kelso', 'Kelso'), ('Wetherby', 'Wetherby'), ('Catterick Bridge', 'Catterick Bridge'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Thirsk', 'Thirsk'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Aintree', 'Aintree'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Kelso', 'Kelso'), ('Wetherby', 'Wetherby'), ('Catterick Bridge', 'Catterick Bridge'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Thirsk', 'Thirsk'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Aintree', 'Aintree'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Kelso', 'Kelso'), ('Wetherby', 'Wetherby'), ('Catterick Bridge', 'Catterick Bridge'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Thirsk', 'Thirsk'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Aintree', 'Aintree'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Kelso', 'Kelso'), ('Wetherby', 'Wetherby'), ('Catterick Bridge', 'Catterick Bridge'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Thirsk', 'Thirsk'), ('Chester', 'Chester'), ('Taunton', 'Taunton'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Goodwood', 'Goodwood'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Aintree', 'Aintree'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Ayr', 'Ayr'), ('Carlisle', 'Carlisle'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Huntingdon', 'Huntingdon'), ('Kelso', 'Kelso'), ('Wetherby', 'Wetherby'), ('Catterick Bridge', 'Catterick Bridge'), ('York', 'York'), ('Perth', 'Perth'), ('Leicester', 'Leicester'), ('Hamilton', 'Hamilton Park'), ('Exeter', 'Exeter')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('Lost', 'Lost'), ('In Repair', 'In Repair'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
    ]
