# Generated by Django 3.0.5 on 2021-01-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0006_auto_20201231_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Returned for Investigation', 'Returned for Investigation'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('In Repair', 'In Repair'), ('Good Performance', 'Good Performance'), ('Never Worked', 'Refurb'), ('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('No Solid Orange', 'No Solid Orange')], default='In Service', max_length=30),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Perth', 'Perth'), ('Musselburgh', 'Musselburgh'), ('Hamilton', 'Hamilton Park'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('York', 'York'), ('Chester', 'Chester'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Huntingdon', 'Huntingdon'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Salisbury', 'Salisbury'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Goodwood', 'Goodwood'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Returned for Investigation', 'Returned for Investigation'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('In Repair', 'In Repair'), ('Good Performance', 'Good Performance'), ('Never Worked', 'Refurb'), ('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('No Solid Orange', 'No Solid Orange')], default='In Service', max_length=30),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Perth', 'Perth'), ('Musselburgh', 'Musselburgh'), ('Hamilton', 'Hamilton Park'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('York', 'York'), ('Chester', 'Chester'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Huntingdon', 'Huntingdon'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Salisbury', 'Salisbury'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Goodwood', 'Goodwood'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Returned for Investigation', 'Returned for Investigation'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('In Repair', 'In Repair'), ('Good Performance', 'Good Performance'), ('Never Worked', 'Refurb'), ('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('No Solid Orange', 'No Solid Orange')], default='In Service', max_length=30),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Perth', 'Perth'), ('Musselburgh', 'Musselburgh'), ('Hamilton', 'Hamilton Park'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('York', 'York'), ('Chester', 'Chester'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Huntingdon', 'Huntingdon'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Salisbury', 'Salisbury'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Goodwood', 'Goodwood'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Returned for Investigation', 'Returned for Investigation'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('In Repair', 'In Repair'), ('Good Performance', 'Good Performance'), ('Never Worked', 'Refurb'), ('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('No Solid Orange', 'No Solid Orange')], default='In Service', max_length=30),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Perth', 'Perth'), ('Musselburgh', 'Musselburgh'), ('Hamilton', 'Hamilton Park'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('York', 'York'), ('Chester', 'Chester'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Huntingdon', 'Huntingdon'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Salisbury', 'Salisbury'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Goodwood', 'Goodwood'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Returned for Investigation', 'Returned for Investigation'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('In Repair', 'In Repair'), ('Good Performance', 'Good Performance'), ('Never Worked', 'Refurb'), ('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('No Solid Orange', 'No Solid Orange')], default='In Service', max_length=30),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Perth', 'Perth'), ('Musselburgh', 'Musselburgh'), ('Hamilton', 'Hamilton Park'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('York', 'York'), ('Chester', 'Chester'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Huntingdon', 'Huntingdon'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Salisbury', 'Salisbury'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Goodwood', 'Goodwood'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('Returned for Investigation', 'Returned for Investigation'), ('Refurb', 'Refurb'), ('No Solid White', 'No Solid White'), ('Stick', 'Stick'), ('Missing', 'Missing'), ('In Repair', 'In Repair'), ('Good Performance', 'Good Performance'), ('Never Worked', 'Refurb'), ('Failed Battery', 'Failed Battery'), ('Failed', 'Failed'), ('No Solid Orange', 'No Solid Orange')], default='In Service', max_length=30),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Epsom Downs', 'Epsom Downs'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Perth', 'Perth'), ('Musselburgh', 'Musselburgh'), ('Hamilton', 'Hamilton Park'), ('Ayr', 'Ayr'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('York', 'York'), ('Chester', 'Chester'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Huntingdon', 'Huntingdon'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Market Rasen', 'Market Rasen'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Kelso', 'Kelso'), ('Salisbury', 'Salisbury'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Goodwood', 'Goodwood'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
    ]
