# Generated by Django 3.0.5 on 2021-07-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0006_remove_entry_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='status_tmp',
            new_name='status',
        ),
    ]
