# Generated by Django 3.0.5 on 2021-01-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0007_auto_20210106_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='on_course_racing',
            field=models.CharField(blank=True, choices=[('Not to course', 'Not to course'), ('Stuck on track', 'Stuck on track'), ('Good Performance', 'Good Performance')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='on_course_test',
            field=models.CharField(blank=True, choices=[('No Orange', 'No Orange'), ('Broken Switch', 'Broken Switch'), ('Broken Connector', 'Broken Connector'), ('No Solid White', 'No Solid White'), ('Out of Service and returned for Refurb', 'Out of Service and returned for Refurb'), ('No Red', 'No Red')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('Stick', 'Stick'), ('Failed Battery', 'Failed Battery'), ('Missing', 'Missing'), ('Refurb', 'Refurb'), ('Failed', 'Failed'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('No Solid White', 'No Solid White'), ('In Repair', 'In Repair'), ('Good Performance', 'Good Performance'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('Damaged Case', 'Damaged Case'), ('Returned for Investigation', 'Returned for Investigation')], default='In Service', max_length=30),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Market Rasen', 'Market Rasen'), ('Hamilton', 'Hamilton Park'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Warwick', 'Warwick'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Kempton Park', 'Kempton Park'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Beverly', 'Beverly'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('Stick', 'Stick'), ('Failed Battery', 'Failed Battery'), ('Missing', 'Missing'), ('Refurb', 'Refurb'), ('Failed', 'Failed'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('No Solid White', 'No Solid White'), ('In Repair', 'In Repair'), ('Good Performance', 'Good Performance'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('Damaged Case', 'Damaged Case'), ('Returned for Investigation', 'Returned for Investigation')], default='In Service', max_length=30),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Market Rasen', 'Market Rasen'), ('Hamilton', 'Hamilton Park'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Warwick', 'Warwick'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Kempton Park', 'Kempton Park'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Beverly', 'Beverly'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('Stick', 'Stick'), ('Failed Battery', 'Failed Battery'), ('Missing', 'Missing'), ('Refurb', 'Refurb'), ('Failed', 'Failed'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('No Solid White', 'No Solid White'), ('In Repair', 'In Repair'), ('Good Performance', 'Good Performance'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('Damaged Case', 'Damaged Case'), ('Returned for Investigation', 'Returned for Investigation')], default='In Service', max_length=30),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Market Rasen', 'Market Rasen'), ('Hamilton', 'Hamilton Park'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Warwick', 'Warwick'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Kempton Park', 'Kempton Park'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Beverly', 'Beverly'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('Send for mechanical repair', 'Send for mechanical repair'), ('Broken beyond repair', 'Broken beyond repair'), ('No reply from modem', 'No reply from modem'), ('Fixed and returning to course', 'Fixed and returning to course')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Market Rasen', 'Market Rasen'), ('Hamilton', 'Hamilton Park'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Warwick', 'Warwick'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Kempton Park', 'Kempton Park'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Beverly', 'Beverly'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('Stick', 'Stick'), ('Failed Battery', 'Failed Battery'), ('Missing', 'Missing'), ('Refurb', 'Refurb'), ('Failed', 'Failed'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('No Solid White', 'No Solid White'), ('In Repair', 'In Repair'), ('Good Performance', 'Good Performance'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('Damaged Case', 'Damaged Case'), ('Returned for Investigation', 'Returned for Investigation')], default='In Service', max_length=30),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Market Rasen', 'Market Rasen'), ('Hamilton', 'Hamilton Park'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Warwick', 'Warwick'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Kempton Park', 'Kempton Park'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Beverly', 'Beverly'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('Stick', 'Stick'), ('Failed Battery', 'Failed Battery'), ('Missing', 'Missing'), ('Refurb', 'Refurb'), ('Failed', 'Failed'), ('Connector Broken', 'Connector Broken'), ('Never Worked', 'Refurb'), ('No Solid White', 'No Solid White'), ('In Repair', 'In Repair'), ('Good Performance', 'Good Performance'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('Damaged Case', 'Damaged Case'), ('Returned for Investigation', 'Returned for Investigation')], default='In Service', max_length=30),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Market Rasen', 'Market Rasen'), ('Hamilton', 'Hamilton Park'), ('Goodwood', 'Goodwood'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Warwick', 'Warwick'), ('Cheltenham', 'Cheltenham'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Huntingdon', 'Huntingdon'), ('Cartmel', 'Cartmel'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Ludlow', 'Ludlow'), ('Perth', 'Perth'), ('Catterick Bridge', 'Catterick Bridge'), ('Wincanton', 'Wincanton'), ('Haydock', 'Haydock Park'), ('Exeter', 'Exeter'), ('Kempton Park', 'Kempton Park'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Beverly', 'Beverly'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('York', 'York'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
    ]
