# Generated by Django 3.0.5 on 2021-07-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0007_auto_20210706_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_added',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='start_date',
        ),
    ]
