# Generated by Django 3.0.5 on 2021-07-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0008_auto_20210706_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='group',
            new_name='tracker_group',
        ),
        migrations.AlterUniqueTogether(
            name='tracker',
            unique_together={('number', 'tracker_group')},
        ),
    ]
