# Generated by Django 3.0.5 on 2021-01-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0010_auto_20210107_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb: Fixed and returning to course', 'In Refurb: Fixed and returning to course'), ('On course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb: Broken beyond repair', 'In Refurb: Broken beyond repair'), ('On course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On course - Test: No Red', 'On course - Test: No Red'), ('On course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb: Send for mechanical repair', 'In Refurb: Send for mechanical repair'), ('On course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and returned for Refurb', 'Out of Service and returned for Refurb'), ('On course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb: No reply from modem', 'In Refurb: No reply from modem'), ('On course - Test: No Solid White', 'On course - Test: No Solid White'), ('On course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=40),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Goodwood', 'Goodwood'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb: Fixed and returning to course', 'In Refurb: Fixed and returning to course'), ('On course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb: Broken beyond repair', 'In Refurb: Broken beyond repair'), ('On course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On course - Test: No Red', 'On course - Test: No Red'), ('On course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb: Send for mechanical repair', 'In Refurb: Send for mechanical repair'), ('On course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and returned for Refurb', 'Out of Service and returned for Refurb'), ('On course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb: No reply from modem', 'In Refurb: No reply from modem'), ('On course - Test: No Solid White', 'On course - Test: No Solid White'), ('On course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=40),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Goodwood', 'Goodwood'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb: Fixed and returning to course', 'In Refurb: Fixed and returning to course'), ('On course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb: Broken beyond repair', 'In Refurb: Broken beyond repair'), ('On course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On course - Test: No Red', 'On course - Test: No Red'), ('On course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb: Send for mechanical repair', 'In Refurb: Send for mechanical repair'), ('On course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and returned for Refurb', 'Out of Service and returned for Refurb'), ('On course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb: No reply from modem', 'In Refurb: No reply from modem'), ('On course - Test: No Solid White', 'On course - Test: No Solid White'), ('On course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=40),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Goodwood', 'Goodwood'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('In Refurb: Fixed and returning to course', 'In Refurb: Fixed and returning to course'), ('On course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb: Broken beyond repair', 'In Refurb: Broken beyond repair'), ('On course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On course - Test: No Red', 'On course - Test: No Red'), ('On course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb: Send for mechanical repair', 'In Refurb: Send for mechanical repair'), ('On course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and returned for Refurb', 'Out of Service and returned for Refurb'), ('On course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb: No reply from modem', 'In Refurb: No reply from modem'), ('On course - Test: No Solid White', 'On course - Test: No Solid White'), ('On course - Test: No Orange', 'On course - Test: No Orange')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Goodwood', 'Goodwood'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Cartmel', 'Cartmel')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb: Fixed and returning to course', 'In Refurb: Fixed and returning to course'), ('On course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb: Broken beyond repair', 'In Refurb: Broken beyond repair'), ('On course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On course - Test: No Red', 'On course - Test: No Red'), ('On course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb: Send for mechanical repair', 'In Refurb: Send for mechanical repair'), ('On course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and returned for Refurb', 'Out of Service and returned for Refurb'), ('On course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb: No reply from modem', 'In Refurb: No reply from modem'), ('On course - Test: No Solid White', 'On course - Test: No Solid White'), ('On course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=40),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Goodwood', 'Goodwood'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb: Fixed and returning to course', 'In Refurb: Fixed and returning to course'), ('On course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb: Broken beyond repair', 'In Refurb: Broken beyond repair'), ('On course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On course - Test: No Red', 'On course - Test: No Red'), ('On course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb: Send for mechanical repair', 'In Refurb: Send for mechanical repair'), ('On course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and returned for Refurb', 'Out of Service and returned for Refurb'), ('On course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb: No reply from modem', 'In Refurb: No reply from modem'), ('On course - Test: No Solid White', 'On course - Test: No Solid White'), ('On course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=40),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Catterick Bridge', 'Catterick Bridge'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Goodwood', 'Goodwood'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Market Rasen', 'Market Rasen'), ('York', 'York'), ('Pontefract', 'Pontefract'), ('Kempton Park', 'Kempton Park'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Cheltenham', 'Cheltenham'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
    ]
