# Generated by Django 3.0.5 on 2021-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0010_auto_20210706_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='category',
            field=models.CharField(choices=[('Working', 'Working'), ('Warning', 'Warning'), ('Failure', 'Failure'), ('Repair', 'Repair'), ('OOA', 'Out of Action'), ('OOS', 'Out of Service')], max_length=15),
        ),
    ]
