# Generated by Django 3.0.5 on 2021-07-09 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0011_auto_20210708_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
