# Generated by Django 3.0.5 on 2021-01-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0012_auto_20210107_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('York', 'York'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Taunton', 'Taunton'), ('Sandown Park', 'Sandown Park'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Huntingdon', 'Huntingdon'), ('Beverly', 'Beverly'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('York', 'York'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Taunton', 'Taunton'), ('Sandown Park', 'Sandown Park'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Huntingdon', 'Huntingdon'), ('Beverly', 'Beverly'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('York', 'York'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Taunton', 'Taunton'), ('Sandown Park', 'Sandown Park'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Huntingdon', 'Huntingdon'), ('Beverly', 'Beverly'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('York', 'York'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Taunton', 'Taunton'), ('Sandown Park', 'Sandown Park'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Huntingdon', 'Huntingdon'), ('Beverly', 'Beverly'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('York', 'York'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Taunton', 'Taunton'), ('Sandown Park', 'Sandown Park'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Huntingdon', 'Huntingdon'), ('Beverly', 'Beverly'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('York', 'York'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Epsom Downs', 'Epsom Downs'), ('Taunton', 'Taunton'), ('Sandown Park', 'Sandown Park'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Ayr', 'Ayr'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Huntingdon', 'Huntingdon'), ('Beverly', 'Beverly'), ('Wetherby', 'Wetherby'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Kempton Park', 'Kempton Park'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Wincanton', 'Wincanton'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
    ]
