# Generated by Django 3.0.5 on 2021-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0013_auto_20210107_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Perth', 'Perth'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Leicester', 'Leicester'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('York', 'York'), ('Exeter', 'Exeter'), ('Cartmel', 'Cartmel'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Perth', 'Perth'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Leicester', 'Leicester'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('York', 'York'), ('Exeter', 'Exeter'), ('Cartmel', 'Cartmel'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Perth', 'Perth'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Leicester', 'Leicester'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('York', 'York'), ('Exeter', 'Exeter'), ('Cartmel', 'Cartmel'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Perth', 'Perth'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Leicester', 'Leicester'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('York', 'York'), ('Exeter', 'Exeter'), ('Cartmel', 'Cartmel'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Perth', 'Perth'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Leicester', 'Leicester'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('York', 'York'), ('Exeter', 'Exeter'), ('Cartmel', 'Cartmel'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Chester', 'Chester'), ('Hamilton', 'Hamilton Park'), ('Newbury', 'Newbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Carlisle', 'Carlisle'), ('Perth', 'Perth'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Epsom Downs', 'Epsom Downs'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Leicester', 'Leicester'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Haydock', 'Haydock Park'), ('Wincanton', 'Wincanton'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Warwick', 'Warwick'), ('Redcar', 'Redcar'), ('York', 'York'), ('Exeter', 'Exeter'), ('Cartmel', 'Cartmel'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Musselburgh', 'Musselburgh'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Cheltenham', 'Cheltenham')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
    ]
