# Generated by Django 3.0.5 on 2021-01-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0013_auto_20210107_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Hamilton', 'Hamilton Park'), ('York', 'York'), ('Leicester', 'Leicester'), ('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Musselburgh', 'Musselburgh'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Haydock', 'Haydock Park'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Hamilton', 'Hamilton Park'), ('York', 'York'), ('Leicester', 'Leicester'), ('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Musselburgh', 'Musselburgh'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Haydock', 'Haydock Park'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Hamilton', 'Hamilton Park'), ('York', 'York'), ('Leicester', 'Leicester'), ('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Musselburgh', 'Musselburgh'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Haydock', 'Haydock Park'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Hamilton', 'Hamilton Park'), ('York', 'York'), ('Leicester', 'Leicester'), ('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Musselburgh', 'Musselburgh'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Haydock', 'Haydock Park'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('Catterick Bridge', 'Catterick Bridge')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Hamilton', 'Hamilton Park'), ('York', 'York'), ('Leicester', 'Leicester'), ('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Musselburgh', 'Musselburgh'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Haydock', 'Haydock Park'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Market Rasen', 'Market Rasen'), ('Perth', 'Perth'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Warwick', 'Warwick'), ('Hamilton', 'Hamilton Park'), ('York', 'York'), ('Leicester', 'Leicester'), ('Newmarket', 'Newmarket'), ('Pontefract', 'Pontefract'), ('Musselburgh', 'Musselburgh'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Haydock', 'Haydock Park'), ('Goodwood', 'Goodwood'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Chester', 'Chester'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Ayr', 'Ayr'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('Catterick Bridge', 'Catterick Bridge')], default='Kempton Park', max_length=18, null=True),
        ),
    ]
