# Generated by Django 3.0.5 on 2021-01-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0014_auto_20210107_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Leicester', 'Leicester'), ('Redcar', 'Redcar'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Catterick Bridge', 'Catterick Bridge'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Leicester', 'Leicester'), ('Redcar', 'Redcar'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Catterick Bridge', 'Catterick Bridge'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Leicester', 'Leicester'), ('Redcar', 'Redcar'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Catterick Bridge', 'Catterick Bridge'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Leicester', 'Leicester'), ('Redcar', 'Redcar'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Catterick Bridge', 'Catterick Bridge'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Leicester', 'Leicester'), ('Redcar', 'Redcar'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Catterick Bridge', 'Catterick Bridge'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Leicester', 'Leicester'), ('Redcar', 'Redcar'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Catterick Bridge', 'Catterick Bridge'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.CreateModel(
            name='Other_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair')], default='In Service', max_length=41)),
                ('venue', models.CharField(blank=True, choices=[('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Aintree', 'Aintree'), ('Ayr', 'Ayr'), ('Kempton Park', 'Kempton Park'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ludlow', 'Ludlow'), ('Exeter', 'Exeter'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Leicester', 'Leicester'), ('Redcar', 'Redcar'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Cartmel', 'Cartmel'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Catterick Bridge', 'Catterick Bridge'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Newbury', 'Newbury'), ('Chester', 'Chester'), ('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18, null=True)),
                ('comments', models.TextField(blank=True)),
                ('frankel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_logs.Frankel')),
            ],
            options={
                'verbose_name_plural': 'other entries',
            },
        ),
    ]
