# Generated by Django 3.0.5 on 2021-01-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0015_auto_20210108_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Kempton Park', 'Kempton Park'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Sandown Park', 'Sandown Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Thirsk', 'Thirsk'), ('York', 'York'), ('Beverly', 'Beverly'), ('Goodwood', 'Goodwood'), ('Perth', 'Perth')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Kempton Park', 'Kempton Park'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Sandown Park', 'Sandown Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Thirsk', 'Thirsk'), ('York', 'York'), ('Beverly', 'Beverly'), ('Goodwood', 'Goodwood'), ('Perth', 'Perth')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Kempton Park', 'Kempton Park'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Sandown Park', 'Sandown Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Thirsk', 'Thirsk'), ('York', 'York'), ('Beverly', 'Beverly'), ('Goodwood', 'Goodwood'), ('Perth', 'Perth')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Kempton Park', 'Kempton Park'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Sandown Park', 'Sandown Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Thirsk', 'Thirsk'), ('York', 'York'), ('Beverly', 'Beverly'), ('Goodwood', 'Goodwood'), ('Perth', 'Perth')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Kempton Park', 'Kempton Park'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Sandown Park', 'Sandown Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Thirsk', 'Thirsk'), ('York', 'York'), ('Beverly', 'Beverly'), ('Goodwood', 'Goodwood'), ('Perth', 'Perth')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Leicester', 'Leicester'), ('Kempton Park', 'Kempton Park'), ('Newbury', 'Newbury'), ('Cheltenham', 'Cheltenham'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Kelso', 'Kelso'), ('Warwick', 'Warwick'), ('Wincanton', 'Wincanton'), ('Carlisle', 'Carlisle'), ('Pontefract', 'Pontefract'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Haydock', 'Haydock Park'), ('Chester', 'Chester'), ('Salisbury', 'Salisbury'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Hamilton', 'Hamilton Park'), ('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Epsom Downs', 'Epsom Downs'), ('Sandown Park', 'Sandown Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Thirsk', 'Thirsk'), ('York', 'York'), ('Beverly', 'Beverly'), ('Goodwood', 'Goodwood'), ('Perth', 'Perth')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
    ]
