# Generated by Django 3.0.5 on 2021-01-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0015_auto_20210107_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Warwick', 'Warwick'), ('Musselburgh', 'Musselburgh'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Sandown Park', 'Sandown Park'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cartmel', 'Cartmel'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Haydock', 'Haydock Park'), ('Carlisle', 'Carlisle'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Warwick', 'Warwick'), ('Musselburgh', 'Musselburgh'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Sandown Park', 'Sandown Park'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cartmel', 'Cartmel'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Haydock', 'Haydock Park'), ('Carlisle', 'Carlisle'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Warwick', 'Warwick'), ('Musselburgh', 'Musselburgh'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Sandown Park', 'Sandown Park'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cartmel', 'Cartmel'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Haydock', 'Haydock Park'), ('Carlisle', 'Carlisle'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Warwick', 'Warwick'), ('Musselburgh', 'Musselburgh'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Sandown Park', 'Sandown Park'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cartmel', 'Cartmel'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Haydock', 'Haydock Park'), ('Carlisle', 'Carlisle'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Warwick', 'Warwick'), ('Musselburgh', 'Musselburgh'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Sandown Park', 'Sandown Park'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cartmel', 'Cartmel'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Haydock', 'Haydock Park'), ('Carlisle', 'Carlisle'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Warwick', 'Warwick'), ('Musselburgh', 'Musselburgh'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Sandown Park', 'Sandown Park'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cartmel', 'Cartmel'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Haydock', 'Haydock Park'), ('Carlisle', 'Carlisle'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Warwick', 'Warwick'), ('Musselburgh', 'Musselburgh'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Sandown Park', 'Sandown Park'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Chester', 'Chester'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cartmel', 'Cartmel'), ('Redcar', 'Redcar'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Huntingdon', 'Huntingdon'), ('Aintree', 'Aintree'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('York', 'York'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Pontefract', 'Pontefract'), ('Beverly', 'Beverly'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Haydock', 'Haydock Park'), ('Carlisle', 'Carlisle'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
    ]
