# Generated by Django 3.0.5 on 2021-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0016_auto_20210107_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Thirsk', 'Thirsk'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Catterick Bridge', 'Catterick Bridge'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton'), ('Chester', 'Chester'), ('Huntingdon', 'Huntingdon'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso'), ('Aintree', 'Aintree'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Haydock', 'Haydock Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Sandown Park', 'Sandown Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Thirsk', 'Thirsk'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Catterick Bridge', 'Catterick Bridge'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton'), ('Chester', 'Chester'), ('Huntingdon', 'Huntingdon'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso'), ('Aintree', 'Aintree'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Haydock', 'Haydock Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Sandown Park', 'Sandown Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Thirsk', 'Thirsk'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Catterick Bridge', 'Catterick Bridge'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton'), ('Chester', 'Chester'), ('Huntingdon', 'Huntingdon'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso'), ('Aintree', 'Aintree'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Haydock', 'Haydock Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Sandown Park', 'Sandown Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Thirsk', 'Thirsk'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Catterick Bridge', 'Catterick Bridge'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton'), ('Chester', 'Chester'), ('Huntingdon', 'Huntingdon'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso'), ('Aintree', 'Aintree'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Haydock', 'Haydock Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Sandown Park', 'Sandown Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Thirsk', 'Thirsk'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Catterick Bridge', 'Catterick Bridge'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton'), ('Chester', 'Chester'), ('Huntingdon', 'Huntingdon'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso'), ('Aintree', 'Aintree'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Haydock', 'Haydock Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Sandown Park', 'Sandown Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Thirsk', 'Thirsk'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Catterick Bridge', 'Catterick Bridge'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton'), ('Chester', 'Chester'), ('Huntingdon', 'Huntingdon'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso'), ('Aintree', 'Aintree'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Haydock', 'Haydock Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Sandown Park', 'Sandown Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Thirsk', 'Thirsk'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Catterick Bridge', 'Catterick Bridge'), ('Musselburgh', 'Musselburgh'), ('York', 'York'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton'), ('Chester', 'Chester'), ('Huntingdon', 'Huntingdon'), ('Kempton Park', 'Kempton Park'), ('Ludlow', 'Ludlow'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso'), ('Aintree', 'Aintree'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Newbury', 'Newbury'), ('Hamilton', 'Hamilton Park'), ('Cartmel', 'Cartmel'), ('Cheltenham', 'Cheltenham'), ('Market Rasen', 'Market Rasen'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Redcar', 'Redcar'), ('Nottingham', 'Nottingham'), ('Haydock', 'Haydock Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Sandown Park', 'Sandown Park'), ('Carlisle', 'Carlisle'), ('Leicester', 'Leicester')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('NOT IN SERVICE', 'Not In Service'), ('IN SERVICE', 'In Service'), ('IN REPAIR', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
    ]
