# Generated by Django 3.0.5 on 2021-01-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0016_auto_20210108_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Beverly', 'Beverly'), ('Leicester', 'Leicester'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Musselburgh', 'Musselburgh'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Exeter', 'Exeter')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Beverly', 'Beverly'), ('Leicester', 'Leicester'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Musselburgh', 'Musselburgh'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Exeter', 'Exeter')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Beverly', 'Beverly'), ('Leicester', 'Leicester'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Musselburgh', 'Musselburgh'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Exeter', 'Exeter')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Beverly', 'Beverly'), ('Leicester', 'Leicester'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Musselburgh', 'Musselburgh'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Exeter', 'Exeter')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Beverly', 'Beverly'), ('Leicester', 'Leicester'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Musselburgh', 'Musselburgh'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Exeter', 'Exeter')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Beverly', 'Beverly'), ('Leicester', 'Leicester'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Musselburgh', 'Musselburgh'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Exeter', 'Exeter')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.CreateModel(
            name='Other_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Orange', 'On course - Test: No Orange')], default='In Service', max_length=41)),
                ('venue', models.CharField(blank=True, choices=[('Huntingdon', 'Huntingdon'), ('Hamilton', 'Hamilton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Pontefract', 'Pontefract'), ('Sandown Park', 'Sandown Park'), ('Beverly', 'Beverly'), ('Leicester', 'Leicester'), ('Wincanton', 'Wincanton'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('Nottingham', 'Nottingham'), ('Goodwood', 'Goodwood'), ('Musselburgh', 'Musselburgh'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Haydock', 'Haydock Park'), ('Thirsk', 'Thirsk'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Wetherby', 'Wetherby'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('Newbury', 'Newbury'), ('Taunton', 'Taunton'), ('Kelso', 'Kelso'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Exeter', 'Exeter')], default='Kempton Park', max_length=18, null=True)),
                ('comments', models.TextField(blank=True)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_logs.Other')),
            ],
            options={
                'verbose_name_plural': 'other entries',
            },
        ),
    ]
