# Generated by Django 3.0.5 on 2021-01-08 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0017_auto_20210107_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other_entry',
            name='frankel',
        ),
        migrations.AddField(
            model_name='other_entry',
            name='other',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unit_logs.Other'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('In Service', 'In Service'), ('In Repair', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Wincanton', 'Wincanton'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Market Rasen', 'Market Rasen'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Goodwood', 'Goodwood'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('In Service', 'In Service'), ('In Repair', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Wincanton', 'Wincanton'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Market Rasen', 'Market Rasen'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Goodwood', 'Goodwood'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('In Service', 'In Service'), ('In Repair', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Wincanton', 'Wincanton'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Market Rasen', 'Market Rasen'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Goodwood', 'Goodwood'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Wincanton', 'Wincanton'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Market Rasen', 'Market Rasen'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Goodwood', 'Goodwood'), ('Cartmel', 'Cartmel')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('In Service', 'In Service'), ('In Repair', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Wincanton', 'Wincanton'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Market Rasen', 'Market Rasen'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Goodwood', 'Goodwood'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('In Service', 'In Service'), ('In Repair', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Wincanton', 'Wincanton'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Market Rasen', 'Market Rasen'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Goodwood', 'Goodwood'), ('Cartmel', 'Cartmel')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('In Service', 'In Service'), ('In Repair', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Aintree', 'Aintree'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Wincanton', 'Wincanton'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham'), ('Perth', 'Perth'), ('Haydock', 'Haydock Park'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Exeter', 'Exeter'), ('Chester', 'Chester'), ('Kelso', 'Kelso'), ('Thirsk', 'Thirsk'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Huntingdon', 'Huntingdon'), ('Newmarket', 'Newmarket'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Taunton', 'Taunton'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Musselburgh', 'Musselburgh'), ('Wetherby', 'Wetherby'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Market Rasen', 'Market Rasen'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Warwick', 'Warwick'), ('Epsom Downs', 'Epsom Downs'), ('Goodwood', 'Goodwood'), ('Cartmel', 'Cartmel')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('Not In Service', 'Not In Service'), ('In Service', 'In Service'), ('In Repair', 'In Repair')], default='IN SERVICE', max_length=15),
        ),
    ]
