# Generated by Django 3.0.5 on 2021-02-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0017_auto_20210108_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='kauto',
            name='entry_date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='arkle',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Exeter', 'Exeter'), ('York', 'York'), ('Beverly', 'Beverly'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Exeter', 'Exeter'), ('York', 'York'), ('Beverly', 'Beverly'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Exeter', 'Exeter'), ('York', 'York'), ('Beverly', 'Beverly'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Exeter', 'Exeter'), ('York', 'York'), ('Beverly', 'Beverly'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Exeter', 'Exeter'), ('York', 'York'), ('Beverly', 'Beverly'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Exeter', 'Exeter'), ('York', 'York'), ('Beverly', 'Beverly'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Thirsk', 'Thirsk'), ('Newmarket', 'Newmarket'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Catterick Bridge', 'Catterick Bridge'), ('Ayr', 'Ayr'), ('Chester', 'Chester'), ('Ludlow', 'Ludlow'), ('Goodwood', 'Goodwood'), ('Dundalk', 'Dundalk'), ('Newbury', 'Newbury'), ('Sandown Park', 'Sandown Park'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Exeter', 'Exeter'), ('York', 'York'), ('Beverly', 'Beverly'), ('Redcar', 'Redcar'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Taunton', 'Taunton'), ('Epsom Downs', 'Epsom Downs'), ('Musselburgh', 'Musselburgh'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Kempton Park', 'Kempton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Salisbury', 'Salisbury'), ('Wincanton', 'Wincanton')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
    ]
