# Generated by Django 3.0.5 on 2021-03-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0018_auto_20210226_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kauto',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='kauto',
            name='date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Wincanton', 'Wincanton'), ('Huntingdon', 'Huntingdon'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Perth', 'Perth'), ('Dundalk', 'Dundalk'), ('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Epsom Downs', 'Epsom Downs'), ('Kempton Park', 'Kempton Park'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('York', 'York'), ('Beverly', 'Beverly'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Wincanton', 'Wincanton'), ('Huntingdon', 'Huntingdon'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Perth', 'Perth'), ('Dundalk', 'Dundalk'), ('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Epsom Downs', 'Epsom Downs'), ('Kempton Park', 'Kempton Park'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('York', 'York'), ('Beverly', 'Beverly'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Wincanton', 'Wincanton'), ('Huntingdon', 'Huntingdon'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Perth', 'Perth'), ('Dundalk', 'Dundalk'), ('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Epsom Downs', 'Epsom Downs'), ('Kempton Park', 'Kempton Park'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('York', 'York'), ('Beverly', 'Beverly'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Wincanton', 'Wincanton'), ('Huntingdon', 'Huntingdon'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Perth', 'Perth'), ('Dundalk', 'Dundalk'), ('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Epsom Downs', 'Epsom Downs'), ('Kempton Park', 'Kempton Park'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('York', 'York'), ('Beverly', 'Beverly'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Wincanton', 'Wincanton'), ('Huntingdon', 'Huntingdon'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Perth', 'Perth'), ('Dundalk', 'Dundalk'), ('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Epsom Downs', 'Epsom Downs'), ('Kempton Park', 'Kempton Park'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('York', 'York'), ('Beverly', 'Beverly'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Wincanton', 'Wincanton'), ('Huntingdon', 'Huntingdon'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Perth', 'Perth'), ('Dundalk', 'Dundalk'), ('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Epsom Downs', 'Epsom Downs'), ('Kempton Park', 'Kempton Park'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('York', 'York'), ('Beverly', 'Beverly'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Wincanton', 'Wincanton'), ('Huntingdon', 'Huntingdon'), ('Exeter', 'Exeter'), ('Goodwood', 'Goodwood'), ('Hamilton', 'Hamilton Park'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Perth', 'Perth'), ('Dundalk', 'Dundalk'), ('Catterick Bridge', 'Catterick Bridge'), ('Aintree', 'Aintree'), ('Nottingham', 'Nottingham'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Redcar', 'Redcar'), ('Cartmel', 'Cartmel'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Epsom Downs', 'Epsom Downs'), ('Kempton Park', 'Kempton Park'), ('Pontefract', 'Pontefract'), ('Kelso', 'Kelso'), ('Ludlow', 'Ludlow'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Carlisle', 'Carlisle'), ('Chester', 'Chester'), ('York', 'York'), ('Beverly', 'Beverly'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Sandown Park', 'Sandown Park'), ('Newmarket', 'Newmarket')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('In Service', 'In Service'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
    ]
