# Generated by Django 3.0.5 on 2021-01-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0018_auto_20210108_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Warwick', 'Warwick'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('Chester', 'Chester'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Pontefract', 'Pontefract'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Salisbury', 'Salisbury'), ('York', 'York'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Epsom Downs', 'Epsom Downs'), ('Thirsk', 'Thirsk'), ('Taunton', 'Taunton'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Warwick', 'Warwick'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('Chester', 'Chester'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Pontefract', 'Pontefract'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Salisbury', 'Salisbury'), ('York', 'York'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Epsom Downs', 'Epsom Downs'), ('Thirsk', 'Thirsk'), ('Taunton', 'Taunton'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Warwick', 'Warwick'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('Chester', 'Chester'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Pontefract', 'Pontefract'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Salisbury', 'Salisbury'), ('York', 'York'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Epsom Downs', 'Epsom Downs'), ('Thirsk', 'Thirsk'), ('Taunton', 'Taunton'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Warwick', 'Warwick'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('Chester', 'Chester'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Pontefract', 'Pontefract'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Salisbury', 'Salisbury'), ('York', 'York'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Epsom Downs', 'Epsom Downs'), ('Thirsk', 'Thirsk'), ('Taunton', 'Taunton'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Warwick', 'Warwick'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('Chester', 'Chester'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Pontefract', 'Pontefract'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Salisbury', 'Salisbury'), ('York', 'York'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Epsom Downs', 'Epsom Downs'), ('Thirsk', 'Thirsk'), ('Taunton', 'Taunton'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Warwick', 'Warwick'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('Chester', 'Chester'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Pontefract', 'Pontefract'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Salisbury', 'Salisbury'), ('York', 'York'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Epsom Downs', 'Epsom Downs'), ('Thirsk', 'Thirsk'), ('Taunton', 'Taunton'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Nottingham', 'Nottingham'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle'), ('Kempton Park', 'Kempton Park'), ('Warwick', 'Warwick'), ('Huntingdon', 'Huntingdon'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Leicester', 'Leicester'), ('Catterick Bridge', 'Catterick Bridge'), ('Ludlow', 'Ludlow'), ('Wetherby', 'Wetherby'), ('Perth', 'Perth'), ('Chester', 'Chester'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Haydock', 'Haydock Park'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Cartmel', 'Cartmel'), ('Pontefract', 'Pontefract'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Salisbury', 'Salisbury'), ('York', 'York'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Newmarket', 'Newmarket'), ('Beverly', 'Beverly'), ('Wincanton', 'Wincanton'), ('Ayr', 'Ayr'), ('Epsom Downs', 'Epsom Downs'), ('Thirsk', 'Thirsk'), ('Taunton', 'Taunton'), ('Exeter', 'Exeter'), ('Sandown Park', 'Sandown Park')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('IN REPAIR', 'In Repair'), ('IN SERVICE', 'In Service'), ('NOT IN SERVICE', 'Not In Service')], default='IN SERVICE', max_length=15),
        ),
    ]
