# Generated by Django 3.0.5 on 2021-01-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0019_auto_20210108_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ayr', 'Ayr'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Thirsk', 'Thirsk'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Newbury', 'Newbury'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ayr', 'Ayr'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Thirsk', 'Thirsk'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Newbury', 'Newbury'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ayr', 'Ayr'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Thirsk', 'Thirsk'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Newbury', 'Newbury'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ayr', 'Ayr'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Thirsk', 'Thirsk'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Newbury', 'Newbury'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ayr', 'Ayr'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Thirsk', 'Thirsk'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Newbury', 'Newbury'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ayr', 'Ayr'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Thirsk', 'Thirsk'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Newbury', 'Newbury'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Racing: Not to course', 'On course - racing: Not to course'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Test: No Red', 'On Course - Test: No Red')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Ayr', 'Ayr'), ('Cartmel', 'Cartmel'), ('York', 'York'), ('Haydock', 'Haydock Park'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Wincanton', 'Wincanton'), ('Salisbury', 'Salisbury'), ('Ludlow', 'Ludlow'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Beverly', 'Beverly'), ('Kempton Park', 'Kempton Park'), ('Cheltenham', 'Cheltenham'), ('Nottingham', 'Nottingham'), ('Chester', 'Chester'), ('Perth', 'Perth'), ('Wetherby', 'Wetherby'), ('Pontefract', 'Pontefract'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Aintree', 'Aintree'), ('Sandown Park', 'Sandown Park'), ('Thirsk', 'Thirsk'), ('Catterick Bridge', 'Catterick Bridge'), ('Goodwood', 'Goodwood'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Epsom Downs', 'Epsom Downs'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Musselburgh', 'Musselburgh'), ('Newbury', 'Newbury'), ('Newmarket', 'Newmarket'), ('Kelso', 'Kelso')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('Not In Service', 'Not In Service')], default='In Service', max_length=15),
        ),
    ]
