# Generated by Django 3.0.5 on 2021-01-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0020_auto_20210108_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Kempton Park', 'Kempton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Nottingham', 'Nottingham'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Beverly', 'Beverly'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Newbury', 'Newbury')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Kempton Park', 'Kempton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Nottingham', 'Nottingham'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Beverly', 'Beverly'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Newbury', 'Newbury')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Kempton Park', 'Kempton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Nottingham', 'Nottingham'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Beverly', 'Beverly'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Newbury', 'Newbury')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Kempton Park', 'Kempton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Nottingham', 'Nottingham'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Beverly', 'Beverly'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Newbury', 'Newbury')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Kempton Park', 'Kempton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Nottingham', 'Nottingham'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Beverly', 'Beverly'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Newbury', 'Newbury')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Kempton Park', 'Kempton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Nottingham', 'Nottingham'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Beverly', 'Beverly'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Newbury', 'Newbury')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='status',
            field=models.CharField(choices=[('In Refurb - Broken beyond repair', 'In Refurb - Broken beyond repair'), ('On Course - Racing: Good Performance', 'On course - racing: Good Performance'), ('In Refurb - Send for mechanical repair', 'In Refurb - Send for mechanical repair'), ('On Course - Test: No Orange', 'On course - Test: No Orange'), ('In Refurb - No reply from modem', 'In Refurb - No reply from modem'), ('On Course - Test: No Solid White', 'On course - Test: No Solid White'), ('On Course - Racing: Stuck on track', 'On course - racing: Stuck on track'), ('Out of Service and Returned for Refurb', 'Out of Service and returned for Refurb'), ('On Course - Test: Broken Switch', 'On course - Test: Broken Switch'), ('On Course - Test: Broken Connector', 'On course - Test: Broken Connector'), ('On Course - Test: No Red', 'On Course - Test: No Red'), ('In Refurb - Fixed and returning to course', 'In Refurb - Fixed and returning to course'), ('On Course - Racing: Not to course', 'On course - racing: Not to course')], default='In Service', max_length=41),
        ),
        migrations.AlterField(
            model_name='other_entry',
            name='venue',
            field=models.CharField(blank=True, choices=[('Kempton Park', 'Kempton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Market Rasen', 'Market Rasen'), ('Taunton', 'Taunton'), ('Aintree', 'Aintree'), ('Huntingdon', 'Huntingdon'), ('Ludlow', 'Ludlow'), ('Haydock', 'Haydock Park'), ('Warwick', 'Warwick'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Goodwood', 'Goodwood'), ('Nottingham', 'Nottingham'), ('Sandown Park', 'Sandown Park'), ('Kelso', 'Kelso'), ('Chester', 'Chester'), ('Exeter', 'Exeter'), ('Redcar', 'Redcar'), ('Thirsk', 'Thirsk'), ('Ayr', 'Ayr'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Beverly', 'Beverly'), ('Cheltenham', 'Cheltenham'), ('Newmarket', 'Newmarket'), ('Epsom Downs', 'Epsom Downs'), ('Salisbury', 'Salisbury'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Newbury', 'Newbury')], default='Kempton Park', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('In Repair', 'In Repair'), ('Not In Service', 'Not In Service'), ('In Service', 'In Service')], default='In Service', max_length=15),
        ),
    ]
